### ISSUE TITLE
Need clarification on training 'code2emb' model in Part 4

### ISSUE THREAD

**Issue by ajay-sreeram** [hamelsmu/code_search#29]
Is there any specific reason behind using large batch size(20k), less epochs(15) while training `code2emb_model` by freezing encoder and small batch size(2k), more epochs(20) while training complete model?

**Comment by hamelsmu** [comment]
@ajay-sreeram here is general intuition:

When you freeze model you have less trainable parameters and thus you can push more data through the computation graph without running out of memory.   This is why when we unfreeze the model we decrease the batch size dramatically.

**Comment by ajay-sreeram** [comment]
@hamelsmu I see, thanks for the explanation. 
Actually I learn a lot from your approach and code, thanks a lot again.
