### ISSUE TITLE
Preprocess Data: ModuleNotFoundError: No module named 'general_utils'

### ISSUE THREAD

**Issue by connected-bsamadi** [hamelsmu/code_search#32]
I'm trying to run the Preprocess Process notebook on Google Colab. I was wondering where general_utils comes from. Currently, I get the following error:
ModuleNotFoundError: No module named 'general_utils'

**Comment by connected-bsamadi** [comment]
I found them in the same repository!

**Comment by keilabcs** [comment]
I have the same problem :(
