### ISSUE TITLE
Can't load index?

### ISSUE THREAD

**Issue by Ceceu** [hamelsmu/code_search#34]
Hello,

I am trying to load the index using the code provided in notebook 5:
```
search_index = nmslib.init(method='hnsw', space='cosinesimil')
search_index.loadIndex('./data/search/search_index.nmslib')
```
But, the following error happens:
```
Check failed: data_level0_memory_
Traceback (most recent call last):
search_index.loadIndex("./data/search/search_index.nmslib")
RuntimeError: Check failed: it's either a bug or inconsistent data!

```
My computer has only 8GB as primary memory. So, did this happen because the index is over 8GB and could not be loaded into memory?

Thank you for any help.

**Comment by hamelsmu** [comment]
There is mismatch between the data you are loading and the object you loaded.... Its hard for me to debug with this information.
