### ISSUE TITLE
Part 3 - Training the language model

### ISSUE THREAD

**Issue by Laksh47** [hamelsmu/code_search#35]
Hi @hamelsmu 

Training the language model(**train_lang_model**) seems to take 13 hours and gpu utilization is at 0%.  Why this step does not utilize gpu? Is this intentional? or Is there a configuration that needs to be set to enable gpu utilization?

I verified that the environment variable is set to a gpu device.

**Comment by hamelsmu** [comment]
What kind of GPU do you have?  Are you using the Docker Container in the tutorial?
