### ISSUE TITLE
fastai backward compatibility issue

### ISSUE THREAD

**Issue by rsanchezavalos** [hamelsmu/code_search#40]
The image hamelsmu/ml-gpu is installing the latest version of fastai making some parts of the code to crash. Solved by uninstalling and: `pip install fastai==0.7.0; pip install torchtext==0.2.3` but you could use the requirements.txt specification you also provided on the repo.

**Comment by hamelsmu** [comment]
maybe don't try to build yourself but instead pull from dockerhub?
