### ISSUE TITLE
Pre-Trained Model for Code Search

### ISSUE THREAD

**Issue by vikrant-sahu** [hamelsmu/code_search#68]
Is there a pre-trained model for the code search task? I couldn't find it here or in CodeSearchNet Repository. Pre-Trained model for any of Part 3 or Part 4 can also help.

**Comment by hamelsmu** [comment]
**The techniques presented here are old and have been significantly refined in a subsequent project called [CodeSearchNet](https://github.com/github/codesearchnet), with an associated [paper](https://arxiv.org/abs/1909.09436).**

I recommend looking at the aforementioned project for a more modern approach to this topic
